# Generated by Django 3.2.6 on 2021-08-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='things',
            name='time_updated',
            field=models.DateTimeField(verbose_name='auto_now_add'),
        ),
    ]
