# Generated by Django 3.2.6 on 2021-08-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_alter_things_time_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='things',
            name='time_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
