# Generated by Django 3.2.6 on 2021-08-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_alter_things_time_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='things',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
